### ISSUE TITLE
[0.1.23] Negative byte values before # in args-file prevent starting

### ISSUE THREAD

**Issue by Griefed** [neoforged/ServerStarterJar#1]
## Problem

Running the server.jar, version 0.1.23, produces a `Failed to find main class"?#"`-exception when using a user_jvm_args.txt.

```java
Exception in thread "main" java.lang.Exception: Failed to find main class "?#"
        at net.neoforged.serverstarterjar.Main.mainLaunch(Main.java:225)
        at net.neoforged.serverstarterjar.Main.main(Main.java:70)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.neoforged.serverstarterjar.Main8.main(Main8.java:19)
Caused by: java.lang.ClassNotFoundException: ?#
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:375)
        at net.neoforged.serverstarterjar.Main.mainLaunch(Main.java:223)
        ... 6 more
```

## How to reproduce

1. Download the user_jvm_args.txt in question: [user_jvm_args.txt](https://github.com/user-attachments/files/16322172/user_jvm_args.txt)
2. In a PowerShell terminal, run `& 'path\to\your\java\17' "@user_jvm_args.txt" -jar server.jar --installer https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.19.2-43.2.21/forge-1.19.2-43.2.21-installer.jar`
3. Observe `Exception in thread "main" java.lang.Exception: Failed to find main class "?#"`

### user_jvm_args

The contents of the user_jvm_args are simply:

```
# Xmx and Xms set the maximum and minimum RAM usage, respectively.
# They can take any number, followed by an M or a G.
# M means Megabyte, G means Gigabyte.
# For example, to set the maximum to 3GB: -X
# To set the minimum to 2.5GB: -Xms2500M
# A good default for a modded server is 4GB.
# Uncomment the next line to set it.
# -Xmx4G ddddddddddd
-Xmx4G -Xms4G
```

Created by the start scripts of my app ServerPackCreator at the following positions:
For Windows: https://github.com/Griefed/ServerPackCreator/blob/6a4262a0c598c1a97d24cae67d499ecc82799183/serverpackcreator-api/src/main/resources/de/griefed/resources/server_files/default_template.ps1#L295

For Linux: https://github.com/Griefed/ServerPackCreator/blob/6a4262a0c598c1a97d24cae67d499ecc82799183/serverpackcreator-api/src/main/resources/de/griefed/resources/server_files/default_template.sh#L213

### Pinpointing the error

I've managed to identify the point where the error sneaks its way into the execution: https://github.com/neoforged/ServerStarterJar/blob/dcc86e5110c4d685507c9dc721fe5e5db255b758/src/main/java/net/neoforged/serverstarterjar/Main.java#L392

And I've also identified the source for the error, that being negative values in the byte-array in the first line in the args-file. Haven't been able to figure out *why* it contains negative values, though. If you can think of a reason, then be my guest. See `### user_jvm_args` for how the args-file is created, if you so desire.

The very first line, that being `﻿# Xmx and Xms set the maximum and minimum RAM usage, respectively.` has the following byte[] to it: `[-1, -2, 35, 0, 32, 0, 88, 0, 109, 0, 120, 0, ...]`

The `-1, -2` are particularly strange here. Every other line starts with `35`, which is the `#`. For some reason, though, line 0 doesn't.

As such, `filter(str -> !str.startsWith("#")` doesn't filter out the first line, because technically it doesn't start with `#`, even though it 100% looks like it does in both the file itself, as well as in the value whilst debugging
![image](https://github.com/user-attachments/assets/56bba46e-2448-4c04-93d2-3cde66a8b8f6)

### Workaround

I've managed to get a workaround running by checking whether the line has a `#` in it, and then overwriting the entry in the list with a new string consisting of only the bytes starting from the `#`, effectively removing negative byte-values from any list-entry.

https://github.com/neoforged/ServerStarterJar/compare/main...Griefed:ServerStarterJar:main

Though I hope you have a better, actual, solution to this, as this feels rather hacky.

**Comment by Matyrobbrt** [comment]
Upon further investigation, it seems like this is caused by powershell's out-file always writing a BOM (`-1, -2` specifically) even when encoding with UTF-8 (see https://stackoverflow.com/questions/5596982/using-powershell-to-write-a-file-in-utf-8-without-the-bom). Under these circumstances, I'm not sure if there's a lot I can do here (reading the file with UTF-16 won't work since that's an invalid BOM), you should instead use one of the solutions described in the SO thread I linked.

**Comment by Griefed** [comment]
So it is indeed a garbage in, garbage out thing :D Sorry for bothering you with something caused from my end of things.

I'll take a look into this :)
